export interface Item {
	id: string,
	event_id: string,
	title: string,
	description: string,
	price: number,
	quantity: number,
	quantity_available?: number,
	start_sale_date: string,
	end_sale_date: string,
	status: string,
	created_at: string,
	updated_at: string,
	category?: string,
	color?: string,
	type?: "PAID" | "FREE" | "DONATION" | "INVITE",
	is_hidden?: boolean,
	sort_order?: number,
	gimmick_status?: number,
}
