export interface TicketType {
	id: string,
	event_id: string,
	name: string,
	description: string,
	price: number,
	quantity: number,
	quantity_available?: number,
	start_sale_date: string,
	end_sale_date: string,
	status: string,
	created_at: string,
	updated_at: string,
	category?: string,
	type?: string,
	is_hidden?: boolean,
	sort_order?: number,
	inventory_status?: number,
}
