<?php

namespace App\Http\Controllers;

use App\Repositories\Contracts\EventRepositoryInterface;
use Illuminate\Http\Request;
use Inertia\Inertia;

class EventController extends Controller
{
  protected $eventRepository;

  public function __construct(EventRepositoryInterface $eventRepository)
  {
    $this->eventRepository = $eventRepository;
  }

  public function index(Request $request)
  {
    $params = $request->only(['search', 'limit', 'page']);
    $events = $this->eventRepository->getAll($params);

    return Inertia::render('events/EventIndex', [
      'events' => $events,
      'filters' => $request->only(['search', 'limit']),
    ]);
  }

  public function store(Request $request)
  {
    $validated = $request->validate([
      'name' => 'required|string|max:255',
      'description' => 'nullable|string',
      'start_date' => 'required|date',
      'end_date' => 'required|date|after:start_date',
      'location' => 'required|string',
      'organization_id' => 'required|exists:core_pgsql.organizations,id', // Assuming organization exists
    ]);

    // Generate UUID if not auto-generated by DB, assuming model handles it or DB defaults
    // For now, let's assume the repository/model handles creation logic

    $this->eventRepository->create($validated);

    return redirect()->back()->with('success', 'Event created successfully.');
  }

  public function update(Request $request, string $id)
  {
    $validated = $request->validate([
      'name' => 'required|string|max:255',
      'description' => 'nullable|string',
      'start_date' => 'required|date',
      'end_date' => 'required|date|after:start_date',
      'location' => 'required|string',
    ]);

    $this->eventRepository->update($id, $validated);

    return redirect()->back()->with('success', 'Event updated successfully.');
  }

  public function destroy(string $id)
  {
    $this->eventRepository->delete($id);
    return redirect()->back()->with('success', 'Event deleted successfully.');
  }
}
