<?php

namespace App\Http\Controllers;

use App\Repositories\Contracts\OrganizationRepositoryInterface;
use Illuminate\Http\Request;
use Inertia\Inertia;

class OrganizationController extends Controller
{
  protected $event_repo;

  public function __construct(OrganizationRepositoryInterface $event_repo)
  {
    $this->event_repo = $event_repo;
  }

  public function index(Request $request)
  {
    $params = $request->only(['search', 'limit', 'page']);
    $events = $this->event_repo->getAll($params);

    return Inertia::render('events/OrganizationIndex', [
      'events' => $events,
      'filters' => $request->only(['search', 'limit']),
    ]);
  }

  public function store(Request $request)
  {
    $validated = $request->validate([
      'name' => 'required|string|max:255',
      'description' => 'nullable|string',
      'start_date' => 'required|date',
      'end_date' => 'required|date|after:start_date',
      'timezone' => 'nullable|string|max:50',
      'location' => 'required|string',
      'organization_id' => 'required|exists:core_pgsql.organizations,id', // Assuming organization exists
    ]);

    // Generate UUID if not auto-generated by DB, assuming model handles it or DB defaults
    // For now, let's assume the repository/model handles creation logic

    $this->event_repo->create($validated);

    return redirect()->back()->with('success', 'Organization created successfully.');
  }

  public function update(Request $request, string $id)
  {
    $validated = $request->validate([
      'name' => 'required|string|max:255',
      'description' => 'nullable|string',
      'start_date' => 'required|date',
      'end_date' => 'required|date|after:start_date',
      'timezone' => 'nullable|string|max:50',
      'location' => 'required|string',
    ]);

    $this->event_repo->update($id, $validated);

    return redirect()->back()->with('success', 'Organization updated successfully.');
  }

  public function destroy(string $id)
  {
    $this->event_repo->delete($id);
    return redirect()->back()->with('success', 'Organization deleted successfully.');
  }
}
